### Obtener tareas
GET http://192.168.100.6:4000/task/list

### Crear tarea
POST http://192.168.100.6:4000/task/create
Content-Type: application/json

{
  "title": "Hacer algo",
  "description": ""
}

### Obtener
GET http://192.168.100.6:4000/task?id=62bf2a7b88458b2cc5af336e


### Actualizar tarea
PUT http://192.168.100.6:4000/task?id=62bf2a7b88458b2cc5af336e
Content-Type: application/json

{
  "title": "Molestar a la gata",
  "state": "DOING_STATE"
}

### Eliminar tarea
DELETE http://192.168.100.6:4000/task/?id=62bf2a7b88458b2cc5af336e